export const enum ActionTypes {

    ADD_CARD_START = 'ADD_CARD_START',
    ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS',
    ADD_CARD_FAILURE = 'ADD_CARD_FAILURE',

    ADD_COLUMN_START = 'ADD_COLUMN_START',
    ADD_COLUMN_SUCCESS = 'ADD_COLUMN_SUCCESS',
    ADD_COLUMN_FAILURE = 'ADD_COLUMN_FAILURE',

    UPDATE_CARD_POSITION_START = 'UPDATE_CARD_POSITION_START',
    UPDATE_CARD_POSITION_SUCCESS = 'UPDATE_CARD_POSITION_SUCCESS',
    UPDATE_CARD_POSITION_FAILURE = 'UPDATE_CARD_POSITION_FAILURE',

    UPDATE_COLUMN_POSITION_START = 'UPDATE_COLUMN_POSITION_START',
    UPDATE_COLUMN_POSITION_SUCCESS = 'UPDATE_COLUMN_POSITION_SUCCESS',
    UPDATE_COLUMN_POSITION_FAILURE = 'UPDATE_COLUMN_POSITION_FAILURE',

    DELETE_COLUMN_START = 'DELETE_COLUMN_START',
    DELETE_COLUMN_SUCCESS = 'DELETE_COLUMN_SUCCESS',
    DELETE_COLUMN_FAILURE = 'DELETE_COLUMN_FAILURE',

    DELETE_CARD_START = 'DELETE_CARD_START',
    DELETE_CARD_SUCESS = 'DELETE_CARD_SUCESS',
    DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE',

    RENAME_CARD_START = 'RENAME_CARD_START',
    RENAME_CARD_SUCCESS = 'RENAME_CARD_SUCCESS',
    RENAME_CARD_FAILURE = 'RENAME_CARD_FAILURE',

    RENAME_COLUMN_START = 'RENAME_COLUMN_START',
    RENAME_COLUMN_SUCCESS = 'RENAME_COLUMN_SUCCESS',
    RENAME_COLUMN_FAILURE = 'RENAME_COLUMN_FAILURE',

    GET_DATA_FROM_STORAGE_START = "GET_DATA_FROM_STORAGE_START",
    GET_DATA_FROM_STORAGE_SUCCESS = "GET_DATA_FROM_STORAGE_SUCCESS",
    GET_DATA_FROM_STORAGE_FAILURE = "GET_DATA_FROM_STORAGE_FAILURE",

}


export const START_CARD_ID = 100;

