export const enum ActionTypes {

    ADD_CARD_START = 'ADD_CARD_START',
    ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS',
    ADD_CARD_FAILURE = 'ADD_CARD_FAILURE',

    ADD_COLUMN_START = 'ADD_COLUMN_START',
    ADD_COLUMN_SUCCESS = 'ADD_COLUMN_SUCCESS',
    ADD_COLUMN_FAILURE = 'ADD_COLUMN_FAILURE',

    UPDATE_CARD_POSITION_START = 'UPDATE_CARD_POSITION_START',
    UPDATE_CARD_POSITION_SUCCESS = 'UPDATE_CARD_POSITION_SUCCESS',
    UPDATE_CARD_POSITION_FAILURE = 'UPDATE_CARD_POSITION_FAILURE',

    UPDATE_COLUMN_POSITION_START = 'UPDATE_COLUMN_POSITION_START',
    UPDATE_COLUMN_POSITION_SUCCESS = 'UPDATE_COLUMN_POSITION_SUCCESS',
    UPDATE_COLUMN_POSITION_FAILURE = 'UPDATE_COLUMN_POSITION_FAILURE',

    DELETE_COLUMN_START = 'DELETE_COLUMN_START',
    DELETE_COLUMN_SUCCESS = 'DELETE_COLUMN_SUCCESS',
    DELETE_COLUMN_FAILURE = 'DELETE_COLUMN_FAILURE',

    DELETE_CARD_START = 'DELETE_CARD_START',
    DELETE_CARD_SUCESS = 'DELETE_CARD_SUCESS',
    DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE',

    RENAME_CARD_START = 'RENAME_CARD_START',
    RENAME_CARD_SUCCESS = 'RENAME_CARD_SUCCESS',
    RENAME_CARD_FAILURE = 'RENAME_CARD_FAILURE',

    RENAME_COLUMN_START = 'RENAME_COLUMN_START',
    RENAME_COLUMN_SUCCESS = 'RENAME_COLUMN_SUCCESS',
    RENAME_COLUMN_FAILURE = 'RENAME_COLUMN_FAILURE',

    GET_DATA_FROM_STORAGE_START = "GET_DATA_FROM_STORAGE_START",
    GET_DATA_FROM_STORAGE_SUCCESS = "GET_DATA_FROM_STORAGE_SUCCESS",
    GET_DATA_FROM_STORAGE_FAILURE = "GET_DATA_FROM_STORAGE_FAILURE",

}

/* 
export const ADD_CARD_START = 'ADD_CARD_START';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';

export const UPDATE_CARD_POSITION_START = 'UPDATE_CARD_POSITION_START';
export const UPDATE_CARD_POSITION_SUCCESS = 'UPDATE_CARD_POSITION_SUCCESS';
export const UPDATE_CARD_POSITION_FAILURE = 'UPDATE_CARD_POSITION_FAILURE';

export const UPDATE_COLUMN_POSITION_START = 'UPDATE_COLUMN_POSITION_START';
export const UPDATE_COLUMN_POSITION_SUCCESS = 'UPDATE_COLUMN_POSITION_SUCCESS';
export const UPDATE_COLUMN_POSITION_FAILURE = 'UPDATE_COLUMN_POSITION_FAILURE';

export const DELETE_COLUMN_START = 'DELETE_COLUMN_START';
export const DELETE_COLUMN_SUCCESS = 'DELETE_COLUMN_SUCCESS';
export const DELETE_COLUMN_FAILURE = 'DELETE_COLUMN_FAILURE';

export const DELETE_CARD_START = 'DELETE_CARD_START';
export const DELETE_CARD_SUCESS = 'DELETE_CARD_SUCESS';
export const DELETE_CARD_FAILURE = 'DELETE_CARD_FAILURE';

export const RENAME_CARD_START = 'RENAME_CARD_START';
export const RENAME_CARD_SUCCESS = 'RENAME_CARD_SUCCESS';
export const RENAME_CARD_FAILURE = 'RENAME_CARD_FAILURE';

export const RENAME_COLUMN_START = 'RENAME_COLUMN_START';
export const RENAME_COLUMN_SUCCESS = 'RENAME_COLUMN_SUCCESS';
export const RENAME_COLUMN_FAILURE = 'RENAME_COLUMN_FAILURE';

export const GET_DATA_FROM_STORAGE_START = "GET_DATA_FROM_STORAGE_START";
export const GET_DATA_FROM_STORAGE_SUCCESS = "GET_DATA_FROM_STORAGE_SUCCESS";
export const GET_DATA_FROM_STORAGE_FAILURE = "GET_DATA_FROM_STORAGE_FAILURE";
 */

